### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by atomGit** [Kroc/NoNonsenseForum#242]
i really like the simplicity of nnf, but i'm wondering about the project status since there are several issues open for several years

sometimes well-coded software can live a very long time without changes - is this the case here, or has @Kroc sort of lost interest?

**Comment by Kroc** [comment]
I would like to overhaul NNF but I no longer have the time nor mental capacity I used to and unfortunately the world has moved on; with RSS having been removed from browsers and everything moving to apps, even a better NNF isn't going to make it the better choice over Discord for Getting Things Done in the here and now.

**Comment by foxnoodles** [comment]
> everything moving to apps

this is certainly not true (thank god), Discord will never replace the discussion board format because Discord is a Chat. There are zillions of communities still running forum software and not migrating to Reddit or Discord. 
That being said if you don't have the capacity to maintain the project that is totally fine. Thanks for making it happen in the first place it was one of my favorite bulleting boards for many years.

**Comment by atomGit** [comment]
perhaps he meant _Discourse_, which is bloated garbage in my opinion

also i would say to Kroc that RSS/XML feeds are a _long_ way from extinction - it's still unmatched by any tech i know of and still used heavily by major sites and platforms, such as most CMSs, WordPress, YouTube, Mozilla, etc.

anyway, sorry to hear the news but that's certainly understandable - i think relying solely on RSS for publishing forum content was quite a novel idea
